app.url=https://app-newstaging-shipmentupdates.xbees.in/
hub.url=https://stage-huboperationapp.xbees.in

username=YOUR_EMAIL
password=YOUR_PASSWORD

shipment.id=125581575806
new.hub=DummyHub
expected.hub=DummyHUB(516)

headless=false
timeout=5000
